apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: mysql:5.7
          name: database
          # env:
          #   - name: MYSQL_DATABASE
          #     value: 'db'
          #   - name: MYSQL_USER
          #     value: 'user'
          #   - name: MYSQL_PASSWORD
          #     value: 'password'
          #   - name: MYSQL_ROOT_PASSWORD
          #     value: 'password'
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: mysql-database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mysql-password
          ports:
            - containerPort: 3306
              name: database
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pv-claim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: database
# spec:
#   ports:
#     - port: 3306
#   selector:
#     app: database
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api
# spec:
#   selector:
#     matchLabels:
#       app: api
#   template:
#     metadata:
#       labels:
#         app: api
#     spec:
#       containers:
#         - image: erodotos/api:v0
#           name: api
#           env:
#             - name: DB_HOST
#               value: database
#             - name: DB_PORT
#               value: 3306
#             - name: DB_USER
#               value: user
#             - name: DB_PASSWORD
#               value: password
#             - name: DB_NAME
#               value: db
#           ports:
#             - containerPort: 3000
#               name: api
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api
# spec:
#   ports:
#     - port: 3000
#   selector:
#     app: api