version: '3.9'


services:
  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    networks:
      - backend
    ports:
      - 3307:3306
    volumes:
      - ~/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'


networks:
  backend: