apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: erodotos/api:latest
          name: api
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: '3306'
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: db
          ports:
            - containerPort: 3000
              name: api
          resources:
            requests:
              cpu: 1000m
              memory: 800Mi
            limits:
              cpu: 1000m
              memory: 800Mi